name: Build Android APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      HAS_RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE != '' }}
    steps:
      - uses: actions/checkout@v6

      - name: set up JDK 25
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode Keystore
        run: echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 --decode > app/release.jks
        if: env.HAS_RELEASE_KEYSTORE == 'true'

      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: release.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v6
        with:
          name: XposedSmsCode-APKs
          path: app/build/outputs/apk/release/*.apk

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && env.HAS_RELEASE_KEYSTORE == 'true'
        with:
          draft: true
          files: app/build/outputs/apk/release/*.apk
          body: |
            ## XposedSmsCode Release
            Automated build for version ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
