name: Telegram Notification

on:
  workflow_run:
    types: [completed]
    workflows: [CI, Release]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notification:
    uses: magisk317/magisk-ci-toolkit/.github/workflows/send-telegram-notification.yml@master
    with:
      project_tag: '📌 #XposedSmsCode'
      ci_branch: 'beta'
      release_notes_source: 'docs/CHANGELOG.md'
    secrets:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      TELEGRAM_THREAD_ID: ${{ secrets.TG_THREAD_ID }}
      TELEGRAM_CI_THREAD_ID: ${{ secrets.TG_CI_THREAD_ID }}
