name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-android:
    uses: magisk317/magisk-ci-toolkit/.github/workflows/release-android.yml@master
    with:
      package_name: 'com.github.tianma8023.xposed.smscode'
      modules_repo: 'Xposed-Modules-Repo/com.github.tianma8023.xposed.smscode'
      publish_play: true
      play_track: 'production'
      java_version: '26'
    secrets:
      RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      XPOSED_MODULES_REPO_TOKEN: ${{ secrets.XPOSED_MODULES_REPO_TOKEN }}
      ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
      GH_PAT: ${{ secrets.GH_PAT }}
